#--------------------------------------------------------------------------
# Test
#  - Ubuntu 12.04.4 LTS (GNU/Linux 3.11.0-23-generic x86_64)
# Reference
#  - https://github.com/opinkerfi/adagios/wiki/Installing-Adagios-from-source-on-Debian
# Require:
#  - pynag instell from git.
#    pynag is 0.8.9 in pypi, but few critical fix in git.
#  - Django<=1.5.
#--------------------------------------------------------------------------

- hosts: all
  sudo: yes
  tasks:
    - apt: name={{ item }} update_cache=yes state=installed
      with_items:
        - nagios3
        - check-mk-livestatus
        - git
        - apache2
        - libapache2-mod-wsgi
        - python-django
        - python-simplejson
        - pnp4nagios
        - libgmp-dev
        - python-dev
        - python-paramiko

    # Need to nagios status/restart from adagios
    - copy: src=conf/sudoers-nagios3 dest=/etc/sudoers.d/nagios3
    - file: path=/etc/sudoers.d/nagios3 mode=0440

    - git: repo=https://github.com/pynag/pynag.git dest=/opt/pynag
    - command: python setup.py build   chdir=/opt/pynag
    - command: python setup.py install chdir=/opt/pynag

    - git: repo=https://github.com/opinkerfi/adagios.git dest=/opt/adagios
    - command: cp -r /opt/adagios/adagios/etc/adagios /etc/
    - file: path=/etc/adagios owner=nagios group=nagios recurse=yes
    - file: path=/etc/nagios3 owner=nagios group=nagios recurse=yes
    - file: path=/etc/nagios3/adagios owner=nagios group=nagios state=directory
      notify:
        - adagios-git-init
        - adagios-git-add
        - adagios-git-commit

    - command: sed -i 's|/etc/nagios/nagios.cfg|/etc/nagios3/nagios.cfg|;' /etc/adagios/adagios.conf
    - command: sed -i 's|/etc/nagios/adagios|/etc/nagios3/adagios|;' /etc/adagios/adagios.conf
    - command: sed -i 's|sudo /etc/init.d/nagios|sudo /etc/init.d/nagios3|;' /etc/adagios/adagios.conf
    - command: sed -i 's|nagios_url = "/nagios"|nagios_url = "/nagios3"|;' /etc/adagios/adagios.conf
    - command: sed -i 's|"/usr/sbin/nagios"|"/usr/sbin/nagios3"|;' /etc/adagios/adagios.conf
    - command: sed -i 's|"/usr/share/nagios/html/pnp4nagios/index.php"|"/usr/share/pnp4nagios/html/index.php"|;' /etc/adagios/adagios.conf
    - command: pynag config --append cfg_dir=/etc/nagios3/adagios
    - command: pynag config --append "broker_module=/usr/lib/check_mk/livestatus.o /var/lib/nagios3/rw/livestatus"
    - command: pynag config --set "process_performance_data=1"
    - command: pynag config --append "broker_module=/usr/lib/pnp4nagios/npcdmod.o config_file=/etc/pnp4nagios/npcd.cfg"
    - command: sed -i 's/RUN.*/RUN="yes"/' /etc/default/npcd
    - user: name=nagios groups=www-data append=yes
    - service: name=npcd    state=started enabled=yes
    - service: name=nagios3 state=restarted

    - command: htpasswd -b -c /etc/nagios3/htpasswd.users adagios adagios creates=/etc/nagios3/htpasswd.users
    - copy: src=conf/apache2-adagios.conf dest=/etc/apache2/conf.d/adagios.conf
      notify:
        - restart-apache2

  handlers:
    - name: restart-apache2
      service: name=apache2 state=restarted

    - name: adagios-git-init
      command: git init chdir=/etc/nagios3
      sudo_user: nagios

    - name: adagios-git-add
      command: git add . chdir=/etc/nagios3
      sudo_user: nagios

    - name: adagios-git-commit
      command: git commit -a -m "Initial commit" chdir=/etc/nagios3
      sudo_user: nagios
